/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './posts/**/*.{md,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'text-main': 'var(--color-text)',
        'text-light': 'var(--color-text-light)',
        'bg-main': 'var(--color-background)',
        'sidebar-bg': 'var(--color-sidebar-bg)',
        'border-main': 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        'code-bg': 'var(--color-code-bg)',
        'tag-bg': 'var(--color-tag-bg)',
        'tag-text': 'var(--color-tag-text)',
        'button-bg': 'var(--color-button-bg)',
        'button-hover': 'var(--color-button-hover)',
        'blockquote-bg': 'var(--color-block-quote-bg)',
        'surface-container-low': '#f8f3e9',
        'primary-fixed-dim': '#b4c5ff',
        'surface-container-high': '#ede8de',
        'on-tertiary-fixed': '#360f00',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#121c2b',
        'on-secondary-fixed-variant': '#3d4758',
        outline: '#737686',
        'on-secondary-container': '#596374',
        'surface-bright': '#fef9ef',
        'inverse-primary': '#b4c5ff',
        'on-primary-fixed-variant': '#003ea8',
        'surface-container': '#f2ede3',
        'primary-container': '#2563eb',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#bdc7db',
        'primary-fixed': '#dbe1ff',
        'outline-variant': '#c3c6d7',
        'secondary-container': '#d6e0f5',
        'inverse-on-surface': '#f5f0e6',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb596',
        'surface-container-highest': '#e7e2d8',
        'on-secondary': '#ffffff',
        'on-primary-container': '#eeefff',
        tertiary: '#943700',
        'tertiary-container': '#bc4800',
        'on-tertiary-container': '#ffede6',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#7d2d00',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#00174b',
        'on-surface-variant': '#434655',
        background: '#fef9ef',
        'surface-tint': '#0053db',
        surface: '#fef9ef',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'surface-dim': '#dedad0',
        'surface-variant': '#e7e2d8',
        'on-surface': '#1d1c16',
        'secondary-fixed': '#d9e3f7',
        secondary: '#555f70',
        'inverse-surface': '#32302a',
        'on-background': '#1d1c16',
      },
      fontFamily: {
        'heading': 'var(--font-heading)',
        'body': 'var(--font-body)',
        'headline': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      spacing: {
        'sidebar': 'var(--sidebar-width)',
      },
      maxWidth: {
        'content': 'var(--content-max-width)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
